# hash:sha256:d28cb48df72ecf4d4bcc454364ad66a9e291fe3c253085716cf57f904ec7a5ff
ARG REGISTRY_HOST
FROM $REGISTRY_HOST/codeocean/aind-smartspim-flatfield-estimation:si-0.0.4

ARG DEBIAN_FRONTEND=noninteractive
ARG GIT_ASKPASS
COPY git-ask-pass /
