# hash:sha256:2273321e3b08a99f413fedfec14e6a95b1457f2825cc902793196d877ab18d7a
ARG REGISTRY_HOST
FROM $REGISTRY_HOST/codeocean/aind-smartspim-flatfield-estimation:si-0.0.4

ARG DEBIAN_FRONTEND=noninteractive
ARG GIT_ASKPASS
COPY git-ask-pass /
